### ISSUE TITLE
compiled file using wrong template 

### ISSUE THREAD

**Issue by weihou** [krakenjs/grunt-localizr#16]
It can not compile a file in a subfolder correctly when we have another file that has the same file name on the root.

For example, we have 2 error.dust files. One under the root of the public/templates and another one under public/templates/portal/error folder. Each of them has the corresponding error.properties file.

If you run “grunt build” or “grunt i18n” and check the compiled templates in the .build folder, you can see the one under portal/error is messed up – it uses the template from the root and has snowmen in all content entries. 

If I rename the dust and properties files to portError or just delete the error.properties file on the root, the problem is gone.

**Comment by grawk** [comment]
Hi @weihou. What version of grunt-localizr are you using?

**Comment by aredridel** [comment]
Yeah, I was just noticing that too. There is a test for this in `grunt-localizr@0.2.1`

**Comment by weihou** [comment]
@grawk: we use makara@0.3.8 with grunt-localizr@0.1.4

**Comment by aredridel** [comment]
Update to `grunt-localizr@0.2.1`.

**Comment by weihou** [comment]
Yes, we grunt-localizr@0.2.1 fixed the problem. 

We also need to change the grunt-localizr version to 0.2.1 in makara dependencies.

**Comment by aredridel** [comment]
I've put in a PR to do that. 

Are you still on Kraken 0.7?

**Comment by weihou** [comment]
@aredridel , No, we already upgraded to kraken 1

**Comment by aredridel** [comment]
Ah, usually you use the modules directly in kraken 1.0, not via makara. Just wondering! The PR will land at some point for the grunt-localizr change, but it's not technically backward compatible, so you'll need to manually update.

**Comment by aredridel** [comment]
`makara@1.0.0` is published with these changes (and a lot of trivial version number bumps)
