### ISSUE TITLE
localizing dust files of same name in different directories

### ISSUE THREAD

**Issue by grawk** [krakenjs/grunt-localizr#7]
can result in wrong dust file localized against wrong locale bundle in wrong directory.

E.g.

With dust:
```
public/templates/application/create.dust 
public/templates/create.dust
```

And locale bundles:
```
locales/US/en/application/create.properties 
locales/US/en/create.properties 
```

* grunt-localize will localize application/create.dust with application/create.properties and write to  output/application/create.dust
* grunt-localize will then localize create.dust with application/create.properties and overwrite output/application/create.dust
* grunt-localize will localize create.dust with create.properties and write to output/create.dust

This happens because [fileBundles](https://github.com/krakenjs/grunt-localizr/blob/master/tasks/index.js#L92) will return an array of both create.properties files when it tries to localize templates/create.dust (`[ 'locales/US/en/application/create.properties',
  'locales/US/en/create.properties' ] `). [processWithBundles](https://github.com/krakenjs/grunt-localizr/blob/master/tasks/index.js#L128) then will localize templates/create.dust twice, overwriting output/application/create.dust

**Comment by pvenkatakrishnan** [comment]
This has been fixed.
